### ISSUE TITLE
Dagu web UI on different port

### ISSUE THREAD

**Issue by skizub21** [dagu-labs/dagu#435]
Could you please advise how to change Web UI port?
Also I'm experiencing problem to open web UI pages via my internal IP address used instead of localhost/127.0.0.1

Is it something that can be easily configured in dagu?

**Comment by yohamta** [comment]
Hello @skizub21 ,

Thank you for reaching out with your question! I'm happy to help. When it comes to specifying the host and port for running the Dagu server, there are a couple of ways to do it.

The first way is to specify the `DAGU_HOST` and `DAGU_PORT` environment variables. For example, you could run the following command:
```sh
DAGU_HOST=8000 dagu server
```

The second way is to use the `--host` and `--port` options when running the `dagu server` command. For example:
```sh
dagu server --port=8000
```

I hope this information is helpful to you.

**Comment by skizub21** [comment]
Hi Yohamta,

Just tested both options and it worked. Many thanks for your prompt response!
